version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: weblab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: